server:
  port: 8082

spring:
  application:
    name: apppay
  datasource:
    url: jdbc:mysql://localhost:3307/db_operation
    username: root
    password: Polyglot#2023
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
