version: "3.5"

services:
  mysql:
    image: mysql:8.0.26
    container_name: database-mysql
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=Polyglot#2023
    ports:
    - 3307:3306
    - 33061:33060
    networks:
    - polyglot-test
  sql:
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    container_name: database-sql
    restart: always
    ports:
    - 1434:1433
    environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=Polyglot#2023
    networks:
    - polyglot-test
  postgres:
    image: postgres:alpine3.14
    container_name: database-postgres
    restart: always
    environment:
    - POSTGRES_PASSWORD=Polyglot#2023
    ports:
    - 5434:5432
    networks:
    - polyglot-test
  mongo:
    image: mongo:5.0.2
    container_name: database-mongo
    restart: always
    environment:
    - MONGO_INITDB_ROOT_USERNAME=Polyglot
    - MONGO_INITDB_ROOT_PASSWORD=Polyglot#2023
    ports:
    - 27018:27017
    networks:
    - polyglot-test 

networks:
  polyglot-test:
    name: polyglot-test

