apiVersion: apps/v1

kind: Deployment
metadata:
  name: app-deployment-security
  labels:
    app: security-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: security-service
  template:
    metadata:
      labels:
        app: security-service
    spec:
      containers:
      - name: appsecurity
        image: registry.gitlab.com/villcabo/polyglot-work/appsecurity
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:sqlserver://10.1.11.213:1434;databaseName=db_security;encrypt=true;trustServerCertificate=true;
---
kind: Service
apiVersion: v1
metadata:
  name: secservice
spec:
  type: LoadBalancer
  selector:
    app: security-service
  ports:
  - name: http
    port: 8080
    targetPort: 8080
